### ISSUE TITLE
Tixi3wrapper for Python - functions renamed, code not adapted

### ISSUE THREAD

**Issue by RandomBruno** [DLR-SC/tixi#101]
In tixi3wrapper the functions have been renamed from, for instance, `def getVersion(self)` to `def tixiGetVersion(self)`. 
Unfortunately, in the code of the functions this has not been taken into account and thus it tries to access unknown functions like shown underneath for the initializer trying to use unknown function `getVersion()`.

`def __init__(self):`
`self._handle = ctypes.c_int(-1)`
`self.version = self.getVersion()`

**Comment by rainman110** [comment]
We have already fixed this in commit 84b4cc329df2b
