### ISSUE TITLE
No write routine for arrays available

### ISSUE THREAD

**Issue by sdeinert** [DLR-SC/tixi#103]
The Python interface of Tixi only offers the write routine tixiAddFloatVector for writing MapType=“vector“ elements but no counterpart to create arrays with MapType=“array“.

So far only getter methods for arrays exist in the Python interface. The respective write methods should be added for completeness.

**Comment by ArneBachmann** [comment]
Great idea! Definitely something looking forward to,

**Comment by rainman110** [comment]
Okay, lets think out loudly, how such an API could look like:
 ```c
tixiCreateArray(tixiHandle, "/root/", "myarray", /* ndims */ 2);
tixiSetArrayDimensionName(tixiHandle, "/root/myarray", /* dimIdx */ 1, "machNumber");
tixiSetArrayDimensionName(tixiHandle, "/root/myarray", /* dimIdx */ 2, "angleOfAttack");
tixiSetArrayDimensionValues(tixiHandle, "/root/myarray", /* dimIdx */ 1, myMachValuesArray);
tixiSetArrayDimensionValues(tixiHandle, "/root/myarray", /* dimIdx */ 2, myAoAArray);
tixiSetArrayValues(tixiHandle,  "/root/myarray", myValuesArray);
/* checks, whether all sizes match together. must be called after creation in the end */
tixiCheckArrayIsValid(tixiHandle, "/root/myarray");
```

From the implementation point of view, I could see the problem, that all the array sizes (number of dimension, number of values per dimension) match together as long as we don't have a data structure in between, that checks this (and not only the current XML representation of  it).

Sure, an option would be to silently ignore if the numbers don't match in the end.

**Comment by ArneBachmann** [comment]
I initially implementend the array read functions for TIXI some 7 years ago, but I don't remember  indexing being 1-based in TIXI ... just like Matlab, I guess.

However, I know that one problem was to allocate memory before Python calls, which led to a bloat of function calls to determine the size of the target data structure on the Python side.

If defining the array would be required prior to setting its values, you would avoid the check afterwards and only copy the required number of elements into the allocated memory on the C-side.

**Comment by rainman110** [comment]
We'd actually like to get rid of all array routines, as they are not used anymore in cpacs 3.
