### ISSUE TITLE
Empty xml-nodes are mistreated

### ISSUE THREAD

**Issue by HHOPs** [DLR-SC/tixi#104]
The following node in a CPACS file: ```<damping></damping>``` resulted in ```</damping>```, when using TIXI for parsing and saving (as return file). Only when issueing a dummy number, this behavior was not encountered anymore (e.g. ```<damping>1.0</damping>```). The node itself has not been altered by any utilized TIXI function and was expected to go unaltered from InputFile->OutputFile. Used TIXI version was 3.0.0 with Matlab binding, operating on a CPACS 2.0.1 file.

**Comment by rainman110** [comment]
@HHOPs I don't quite understand the problem yet.

What was the input xml and what is TiXI returning? What should be the expected output instead?

**Comment by rainman110** [comment]
@HHOPs Could it be possible, that tixi does the following for empty nodes:
   
   <damping></damping> -> <damping/>

i.e. with a trailing slash? This is quite standard in XML and is completely valid.

**Comment by HHOPs** [comment]
That's true, sorry for the inquiry!
