### ISSUE TITLE
The TiGL python example fails due to TIXI errors

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/tixi#105]
There is a bug in the python wrapper for TIXI, some of the functions are missing the `tixi` prefix

**Comment by rainman110** [comment]
This was already fixed in one of the lasts commits

**Comment by rainman110** [comment]
https://github.com/DLR-SC/tixi/commit/84b4cc329df2b178918149a96a0aa68b18741da1

**Comment by rainman110** [comment]
Are you sure you are on the lastest master? These issue should have been fixed already

**Comment by joergbrech** [comment]
Yes, but not in the function calls hardcoded in `make_tixi_python.py`, see the variable `userfunctions` and commit 0b7fd842e0f60d5b4c1196bf536634d2aadefb99

**Comment by rainman110** [comment]
Actually, not of the functions should have the prefix tixi! If they have, then it is wrong.

**Comment by rainman110** [comment]
This is, how the wrapper has to look like (taken from TiXI 2.2.4)

[tixiwrapper.zip](https://github.com/DLR-SC/tixi/files/1518495/tixiwrapper.zip)

**Comment by joergbrech** [comment]
Yes, and currently the tixi3wrapper looks like this:

[tixi3wrapper.zip](https://github.com/DLR-SC/tixi/files/1518528/tixi3wrapper.zip)

For instance, the constructor of the Tixi3 class calls `self.getVersion()`, while it only has a member function called `tixiGetVersion`. This gives an error if you try to run the TiGL 3 python demo with the TiXI 3.

**Comment by rainman110** [comment]
This is the wrapper from the release 3.0.0 right? The master (which contains my fix) already look like this:

[tixi3wrapper.zip](https://github.com/DLR-SC/tixi/files/1518549/tixi3wrapper.zip)

**Comment by joergbrech** [comment]
my bad, you are right! I was on the most recent master branch but I must have been looking at the wrong file. I will close the issue!
