### ISSUE TITLE
Inconsisten handling of special characters in text

### ISSUE THREAD

**Issue by melven** [DLR-SC/tixi#107]
Special characters get correctly converted to their XML representation using `addTextElement`.

But when using `getTextElement` one obtains the XML representation...

Example Python code:
```
> from tixiwrapper import Tixi
> t = Tixi()
> doc = t.create('root')
> t.addTextElement('/root','bla','bad < text ! &')
> t.getTextElement('/root/bla')
'bad &lt; text ! &amp;'
```

Not sure if fixing this could break any existing applications, though.

**Comment by ArneBachmann** [comment]
Unquoting that on the roundtrip makes total sense.
One alternative would be to pack everything into a <[CDATA section, but that would break so many other clients and destroy the human-editability of the document.

One other connected issue is encoding in general, is CPACS supposed to be encoded in UTF-8 (the XML default)? How do clients encode text elements, are they supposed to supply encoded strings as byte-arrays to Tixi, or does the TixiWrapper perform encoding from python-internal (usually UTF-16 on Windows until Python 3.5, after that using different Windows APIs) to XML-encoding?

**Comment by rainman110** [comment]
> How do clients encode text elements, are they supposed to supply encoded strings as byte-arrays to Tixi, or does the TixiWrapper perform encoding from python-internal (usually UTF-16 on Windows until Python 3.5, after that using different Windows APIs) to XML-encoding?

We are decoding and encoding it as follows in the python wrapper:

```python
def encode_for_c(thestring):
    if type(thestring) is str:
        return str.encode(thestring)
    else:
        return thestring
        
def decode_for_py(thestring):
    if sys.version_info[0] >= 3:
        return thestring.decode("utf-8")
    else:
        return thestring
```

I am not sure though, if this is correct.

**Comment by ArneBachmann** [comment]
The current recommended approach for untime type checking is `isinstance(obj, str[, more types])` and the encoding doesn´t make sense (?), I guess it should be `thestring.encode("utf_8")` instead

**Comment by rainman110** [comment]
I think this could be handled directly within libxml2 by using libxml2 encoding features which we currently simply ignore.

**Comment by rainman110** [comment]
If we can fix this with a libxml2 setting, this will be included in TiXi 3.1. Otherwise, we'll postpone this issue.

**Comment by rainman110** [comment]
@melven Here's a workaround for your issue: Adding "/text()" at the elements path unescapes the string.

```python
from tixiwrapper import Tixi
t = Tixi()
doc = t.create('root')
t.addTextElement('/root','bla','bad < text ! &')
t.getTextElement('/root/bla/text()')
'bad < text ! &
```

I am working on a fix

**Comment by melven** [comment]
Hi, thanks for looking into this!

**Comment by rainman110** [comment]
@melven I found the issue and fixed it. We will release TiXI 3.1 the next couple of days.

We now have a unit test for it as well:
https://github.com/DLR-SC/tixi/blob/25995a1c2a49bcd9754ad41c6fd9893b434fa452/tests/textelements_check.cpp#L77
