### ISSUE TITLE
Exception message too big

### ISSUE THREAD

**Issue by bernhardmgruber** [DLR-SC/tixi#108]
In the C++ wrapper the function
```
TixiDocumentHandle TixiImportFromString(const std::string& xml)
```
throws an exception if the document could not be constructed (e.g. not well formed). The exception message contains the XML string passed to the function, which might be very large.

In my case, I put the error message in a dialog box and the message's length leads to rendering errors of the dialog box. Although I could solve this issue by shortening the error message myself, I think others might have similar issues when printing the exception message somewhere.

I therefore suggest to remove the xml string from the exception message.

**Comment by rainman110** [comment]
TiXI does not write this error message. It is libxml2 that does it. I could disable the logging mechanism of libxml2 (i.e. make it silent), but isnt't it also pretty useful to see, what the problem actually is?

**Comment by RlanderRISCSW** [comment]
There is another problem: when the error message exceeds 2048 characters tixi crashes with a segmentation fault. Attached you can find an XML file and the corresponding test case for reproducing the error. I think there is a problem with handling the variable argument list (tixiImpl.c:99), from my understanding it is not allowed to reuse `varArgs` after the first call to vsnprintf.
[108_long_exception_message.zip](https://github.com/DLR-SC/tixi/files/3677172/108_long_exception_message.zip)

**Comment by rainman110** [comment]
@RlanderRISCSW I fixed the crashing issue, when the message was larger than 2048 bytes.

I did not change, that the xml string is not printed by libxml, if the xml string is invalid. Is this still required?

If yes, please reopen this issue.
