### ISSUE TITLE
Documentation: transformation in wing 

### ISSUE THREAD

**Issue by MaloDrougard** [DLR-SC/tixi#110]
In the chm documentation for wingElementType, we have:

> Mathematically spoken a element is a coordinate system that is translated, rotated and scaled relative to the section coordinate system. 

But, as far I understand, and as explained in the image of the documentation bellow, the airfoil profile is described in the global coordinates system, then it is transformed by the wingElementType, then it is transformed by the wingSectionType.  

This two definitions does not seems equivalent to me, in particular for rotation. 

![wing-transformation-order](https://user-images.githubusercontent.com/5487810/37967152-cd4efc7e-31ca-11e8-9d07-4b8f32285a31.png)

Best Regards, 
Malo

**Comment by rainman110** [comment]
@MaloDrougard This is CPACS related and does not belong to the tixi xml library. Please post the issue to the https://github.com/DLR-LY/CPACS issue tracker.

**Comment by MaloDrougard** [comment]
Yep, thanks, I put on the wrong github.
