### ISSUE TITLE
Tixi 3 and CMake

### ISSUE THREAD

**Issue by melven** [DLR-SC/tixi#115]
With tixi3 CMake cannot find tixi any more (at least in Windows).

The following files are installed:
```
...
<tixi-install-prefix>/lib/tixi3/tixi-config-version.cmake
<tixi-install-prefix>/lib/tixi3/tixi-config.cmake
<tixi-install-prefix>/lib/tixi3/tixi-targets-release.cmake
<tixi-install-prefix>/lib/tixi3/tixi-targets.cmake
<tixi-install-prefix>/lib/tixi3.lib
...
```
And I adjust the following environment variables:
* add `<tixi-install-prefix>` to `CMAKE_PREFIX_PATH`
* add `<tixi-install-prefix>/lib` to `LIBRARY_PATH`
* add `<tixi-install-prefix>/include` to `INCLUDE`

Then in my CMakeListst.txt I have:
```
find_package(TIXI 2.2.4 REQUIRED MODULE)
```
CMake automatically searches in `<tixi-install-prefix>/lib/tixi/` and for tixi 2.2.4 everything works fine.

Even if I explicitly add `<tixi-install-prefix>/lib/tixi3` CMake will not find tixi.

I'm using the newest CMake version (3.12.0)

**Comment by rainman110** [comment]
We build tigl always with tixi and we never had a problem with finding tixi3. This is, how we search for it:
https://github.com/DLR-SC/tigl/blob/c2f4372aca98a434c0b17444b7c2c89fdd99020b/CMakeLists.txt#L130

**Comment by rainman110** [comment]
The reason why it worked in TiGL was our custom legacy FindTIXI script.

Now, it should be working using ```find_package(tixi3 MODULE)```.

Please test the build from the branch and report, whether your issue has been fixed.
