### ISSUE TITLE
Indexing of text nodes

### ISSUE THREAD

**Issue by bernhardmgruber** [DLR-SC/tixi#118]
Given the following XML 
```
<a>
text1
<b>text2</b>
text3
</a>
```
how do I select text1 or text3? tixiGetTextElement(handle, "/a", ...) yields the concatenation of both text nodes, tixiGetTextElement(handle, "/a/text()[1]", ...) errors with NOT_AN_ELEMENT.

I encountered this problem when parsing documentation comments from CPACS, specifically e.g.:
```<ddue:para>The <ddue:legacyBold>C</ddue:legacyBold>ommon <ddue:legacyBold>P</ddue:legacyBold>arametric ...```

**Comment by rainman110** [comment]
@bernhardmgruber I fixed (at least I tried to) your issue. Now, you should be able to index the different text nodes using the text()[idx] xpath. You you please test this?

**Comment by bernhardmgruber** [comment]
I will see to it in the next couple of days. I guess you did not make a new release, so I need to build TiXI from source for the using it in the CPACS generator?

**Comment by rainman110** [comment]
Sure. I'd like to have your feedback first before making a release.

**Comment by rainman110** [comment]
You can use this build artifact:
https://ci.appveyor.com/api/buildjobs/t3wmfh3432dysmwd/artifacts/_build%2FTIXI-3.0.2-win64.zip

**Comment by bernhardmgruber** [comment]
Iterating over text nodes works now, here is a preview: https://github.com/DLR-SC/tigl/pull/543

However, there seems to still be an issue with handling whitespaces. It looks like text nodes are trimmed (white space is removed left and right). I orignally implemented adding spaces manually between text nodes, but now I cannot correctly translate:
`te<bold>x</bold>t` into `text`, the result is `te x t`.
But when I do not create any space myself, then `one <bold>two</bold> three` (mind the spaces) translate into `onetwothree` as TiXI seems to delete the space after one and the space before three.

I do not need a solution for this now, the text node indexing already provides a big improvement!

**Comment by rainman110** [comment]
In this case, lets merge the PR and close this issue.

We can make another Issue with your descriptions. It is indeed strange. We use a libxml function to concat the strings. Could you please make an issue an describe it in more detail. In particular, what functions you are using to get the whole text.
