### ISSUE TITLE
Unexpected default return values if path does not contain data

### ISSUE THREAD

**Issue by aarondettmann** [DLR-SC/tixi#129]
I have noticed that the function `getDoubleElement(some_path)` will return a float with value 0.0 even if a node does not contain any number-like values. See for instance the following example (I am using the Python interface for Tixi 3.0.3 in Anaconda):

```python
import tixi3.tixi3wrapper as tixiwrapper

CPACS_FILE = 'D150_AGILE_Hangar.xml'

tixi = tixiwrapper.Tixi3()
tixi.open(CPACS_FILE)

xpath = tixi.uIDGetXPath('D150_VAMP_W1_CompSeg1_innerFlap')

# There should be no value to return here
eta = tixi.getDoubleElement(xpath + '/outerShape/innerBorder/etaLE')
print("Path 1:")
print(eta)

# For this path there exists a float value
eta = tixi.getDoubleElement(xpath + '/outerShape/innerBorder/etaLE/eta')
print("Path 2:")
print(eta)
```

This is the XML code at the paths:

```xml
<trailingEdgeDevice uID="D150_VAMP_W1_CompSeg1_innerFlap" xsi:type="trailingEdgeDeviceType">
    <name>D150_VAMP_W1_CompSeg1_innerFlap</name>
    ...
    <outerShape xsi:type="controlSurfaceOuterShapeType">
        <innerBorder xsi:type="controlSurfaceBorderType">
            <etaLE>
                <eta>0.1103</eta>
                <referenceUID>D150_VAMP_W1_CompSeg1_innerFlap</referenceUID>
            </etaLE>
            ...
        </innerBorder>
    </outerShape>
    ...
</trailingEdgeDevice>
```

The output from the Python code is

```
Path 1:
0.0
Path 2:
0.1103
```

This is the CPACS file I used: [D150_AGILE_Hangar.zip](https://github.com/DLR-SC/tixi/files/3514917/D150_AGILE_Hangar.zip)

Similarly, if `getTextElement()` is used instead of `getDoubleElement()`, path 1 will return an empty string but path 2 will return `0.1103` as a string. From the documentation I understand that `NULL` should be returned if there is no value to return (I guess the Python equivalent would be `None`). However, this is not the case.

Wouldn't it alternatively be more intuitive to raise an error instead of returning `None`?

**Comment by joergbrech** [comment]
Thanks for the issue! I agree, that this is not intuitive and the documentation does not correctly describe the behavior of the function. 

In contrast to what the documentation of `tixiGetTextElement` says, xml-Elements of the form

```xml
    <b>
        Text1
        <c>
            15.0
        </c>
        Text2
    </b>
```

are valid and supported by TiXI, which is checked here:

https://github.com/DLR-SC/tixi/blob/8021b7a12e4d2a867e0dec1deeab2e2c0876bab0/tests/textelements_check.cpp#L58

I strongly encourage to support such elements, since TiXI is an xml-parser and not a CPACS-parser. 

The question is, what we would like the expected behavior of `tixiGetTextElement` to be for elements of the form:

```xml
    <b>
        <c>
            15.0
        </c>
    </b>
```

Do we want TiXI to output the default text element, which is an empty string, or do we want it to throw an error?

Note that internally, `tixiGetDoubleElement` calls `tixiGetTextElement` and converts empty strings to zeros.

**Comment by aarondettmann** [comment]
Thanks for the explanation. I didn't know that `<b>Text1<c>...` was allowed, but then I can appreciate the issue.

In case of `GetTextElement()` I could understand that an empty string is returned if there is nothing between two tags, like `<b><c>...`, and since strings aren't delimited by quotation marks. This last point would be crucial to me in the decision to return an empty string.

Still, I am not sure it's logical that `getDoubleElement()` should return 0.0, since there is no float value here. As said before, one could argue that there is an empty string, but I don't see why an empty string/nothing should convert to a number zero.

Just a few more words on the motivation behind this issue: I was using a script where I was asking for a float value at `.../outerShape/innerBorder/etaLE`. This worked fine in CPACS 2.x, since there was a float value under this path. However, in CPACS 3.x the same float value was moved down on layer to `.../innerBorder/etaLE/eta'. Since Tixi didn't throw an error but returned a valid float, it took me some time to debug my code.

All that said, perhaps there are use cases that justify returning 0.0 in this case `<b><c>...`. I don't know enough about XML. What do other XML parsers return in this situation?

**Comment by joergbrech** [comment]
`tixiGetDoubleElement` is implemented in such a way, that it calls `tixiGetTextElement` and than uses `atof` to convert the retrieved string to a double, and `atof` returns 0 for empty strings.

I think ot would make sense to throw either an error or a warning if we try to get text from an empty element. @rainman110, what do you think?

**Comment by rainman110** [comment]
From my side, it would totally make sense to check, whether the text element is actually a number.

If not, we should return ```NO_NUMBER```.
