### ISSUE TITLE
Print line number for validation errors

### ISSUE THREAD

**Issue by sdeinert** [DLR-SC/tixi#131]
Validating a CPACS file against the CPACS schema using tixi produces possibly a large number of error messages/warnings.

For the user it would be very helpful to also print the line number in the CPACS file where the error was encountered. Do you know if this is supported in the libxml?

**Comment by joergbrech** [comment]
We could use the libxml2 function `xmlSchemaSetValidErrors`. For instance, if we test a valid CPACS file `TestData/valid_CPACS_dokumentiert.xml` against a CPACS schema, where the fuselage `positionings` are called `positionings_renamed_for_testing_purposes`, we would get the following output:

```
TestData/valid_CPACS_dokumentiert.xml:2974: element positionings: Schemas validity error : 
Element '{http://www.w3.org/1999/xhtml}positionings': This element is not expected. 
Expected is one of ( {http://www.w3.org/1999/xhtml}parentUID, {http://www.w3.org
/1999/xhtml}positionings_renamed_for_testing_purposes, {http://www.w3.org
/1999/xhtml}fuselageSegments ).
```

Would that help?

See https://travis-ci.org/DLR-SC/tixi/builds/610380269?utm_source=github_status&utm_medium=notification, line 916

**Comment by sdeinert** [comment]
Yes, to me this looks good. This way you have a line number to start sorting out the problem. The only thing that might get a bit irritating is the namespaces or schema locations being printed in front of all the alternatives...

**Comment by joergbrech** [comment]
The tixi test case uses some old cpacs files. I tested this on a newer cpacs file (2.3) and the namespaces are not printed. I get an output that looks somewhat like this: 

```
tests/TestData/simpletest.cpacs.xml:430: element positioningLeadingEdge: Schemas validity error : Element 'positioningLeadingEdge': This element is not expected. Expected is ( stringer ).
tests/TestData/simpletest.cpacs.xml:414: element structure: Schemas validity error : Element 'structure': Missing child element(s). Expected is ( lowerShell ).
tests/TestData/simpletest.cpacs.xml:483: element farField: Schemas validity error : Element 'farField': This element is not expected. Expected is ( tool ).
```
