### ISSUE TITLE
tixi does not support the Matlab API >= R2018a

### ISSUE THREAD

**Issue by JohnDemand** [DLR-SC/tixi#132]
Hi all,

first off, I don't have much experience with make files, so excuse me in case I struggle with trivial problems here.

I'm currently unable to make the Matlab interface for macOS while following Howto
at https://github.com/DLR-SC/tixi/wiki/InstallationHowto

It seems, that configure/generate works fine in CMake. 
![CMake_window](https://user-images.githubusercontent.com/26311396/68073256-6436b100-fd8e-11e9-864d-fd29f03737c4.png)

But in the console, the command 'make' throws a bunch of warnings and ultimately an error (see attached log file)
[tixi_make.log](https://github.com/DLR-SC/tixi/files/3800637/tixi_make.log)

I'm cannot grasp exactly why, but perhaps it's related to the software versions I'm currently using. 
My environment: 
macOS.10.15 (Catalina)
CMake 3.15.0
Matlab 2019.a
I've also tried it with Matlab 2017.a and macOS.10.14 - with no success.

This is my build dir in the end: 
![tixi dir](https://user-images.githubusercontent.com/26311396/68073277-ab24a680-fd8e-11e9-9e79-45b436fdd3e7.png)

In case you require more information, I'm happy to help.
Thank you in advance!

**Comment by rainman110** [comment]
@JohnDemand Thanks for posting your first issue here. Welcome at the TiXI issue tracker!

This looks indeed a bit tricky. You can try to set the CMAKE_OSX_DEPLOYMENT_TARGET to 10.9. This will change some compiler flags.

You could also post your CMakeCache.txt (from the build directory) here to help debugging.

In fact, we don't have matlab around by ourself and just build it occasionally. So the matlab support is definitely a weak point.

**Comment by JohnDemand** [comment]
@rainman110 Thank you for the fast reply.

Setting the CMAKE_OSX_DEPLOYMENT_TARGET to 10.9 didn't solve much unfortunately, as it triggered the same warnings/ error messages. 

Hope this might give you a hint: 
[CMakeCache.txt](https://github.com/DLR-SC/tixi/files/3802087/CMakeCache.txt)

That does make things a bit more complicated, I can imagine. 
Nevertheless, it's appreciated, you actually do offer a Matlab interface.

**Comment by joergbrech** [comment]
The Matlab API changed starting R2018a: https://de.mathworks.com/help/matlab/apiref/mxgetpi.html#mw_11211bd7-0280-4090-b1e5-9744e14986ce

Matlab provides an example on how to support the old and the new API *(copy the next code into Matlab)*:

```matlab
edit([matlabroot '/extern/examples/refbook/convec.c']);
```

Basically, we should use `mxGetComplexDoubles` for R2018a and later, and `mxGetPi` else.

**Comment by joergbrech** [comment]
@JohnDemand, could you please check if the fix in a7f99f480767912047d0190e47f1aab162ec293b resolved your issue? 

To try it out, clone the branch `132-matlab-interleaved complex` branch of tixi into the directory `tixi-issue132` using the following command:

`git clone -b 132-matlab-interleaved-complex https://github.com/DLR-SC/tixi.git tixi-issue132`
