### ISSUE TITLE
XML Schema validation error message does not use tixiMessageHandler

### ISSUE THREAD

**Issue by RlanderRISCSW** [DLR-SC/tixi#135]
The latest change for supporting output of the line numbers during XML Schema validation (ca1181f0e18afb3d4128c0f6036c27ae91adb107) causes that the validation error messages are printed directly to the console instead of using the tixiMessageHandler. Thus it is not possible any more to interpret the error message or forward it to the GUI.

**Comment by rainman110** [comment]
@joergbrech Can you take care of this?
