### ISSUE TITLE
tixiAddFloatVector return error when the added vector is null

### ISSUE THREAD

**Issue by cfsengineering** [DLR-SC/tixi#137]
In the description of the function we can see: 
The Vector to be placed inside the element pointed to by elementPath. If Vector is NULL an empty element will be created.

However when I use the following code (with Python 3.6):
```
    xpath = '/cpacs/vehicles/aircraft/model'
    vector=[]
    tixi.addFloatVector(xpath,'testvect',vector,len(vector),format='%g')
```
It raises the error:
`
   ..., in addFloatVector
    catch_error(errorCode, 'tixiAddFloatVector', parentPath, elementName, vector, numElements, format)
    raise Tixi3Exception(returncode, args, kwargs)
tixi3.tixi3wrapper.Tixi3Exception: FAILED (1) [('tixiAddFloatVector', '/cpacs/vehicles/aircraft/model', 'testvect', [], 0, '%g'), {}] {}
`

but it work fine if vector=[1]

**Comment by joergbrech** [comment]
Hm, you are right, this seems to be an inconsistency in TiXI, that we should fix. According to the documentation of `tixiAddFloatVector` an empty element is created if the input is null:

https://github.com/DLR-SC/tixi/blob/f0d656b2bd5157067f942dd6ce19a6fea95dd4fe/src/tixi.h#L1596-L1597

On the other hand an error is thrown if the new vector has zero elements: 

https://github.com/DLR-SC/tixi/blob/f0d656b2bd5157067f942dd6ce19a6fea95dd4fe/src/tixiImpl.c#L1519-L1521

So the question is what kind of behavior we would like to have. 

 - @cfsengineering, could you please share your use case of adding empty float vectors to your xml?    
 - @rainman110, is there a good reason to disallow adding empty float vectors?

**Comment by cfsengineering** [comment]
To answer your question, it could happen sometime that you do not know in advance if the vector will be empty or not, but it could be useful to have the field created for later in the code.

If it returns an error, it is not a big problem for me, I could test the length of the vector outside this function, it just good if the behaviour of the function fits the description in the documentation :)

**Comment by rainman110** [comment]
@joergbrech In principle, empty vectors should be valid. I am missing though the bigger picture, in which cases this could be a problem.
