### ISSUE TITLE
tixiUIDSetToXPath does not seem to work for me

### ISSUE THREAD

**Issue by Ofnir93** [DLR-SC/tixi#139]
Hello,

I'm trying to add some elements in a CPACS file through a for cycle in Matlab. I can create the new elements path just fine but I cannot seem to add in any way a UID to differentiate between the elements of each iteration. 
When I try to use the tixiUIDSetToXPath function, I always get errror 32 (One or more uID's are not unique) even though I'm using a test UID that I'm sure is not present inside the CPACS database.

What I'm writing is something along these lines:

```
cd(pwd)
IN_file = strcat(pwd, '\Testing.xml');                            
tixi_h = tixiOpenDocument(IN_file);

for i = 1:n
tixiCreateElement(tixi_h, '/cpacs/vehicles/genericElements', 'genericElement');
UID = sprintf('myElement%dID', i);
tixiUIDSetToXPath(tixi_h, '/cpacs/vehicles/genericElements/genericElement' , UID)
end
```

Using this [this](http://tixi.sourceforge.net/Doc/group__UID.html#gae6affe7a9a4daebd4803822bbdb7ad31) as a reference, I think what I wrote should be correct, but maybe I'm missing something. 

Almost forgot, I'm currently using tixi ver. 2.2.4

**EDIT 12/02/2020
I managed to set a uID for my nodes using the function tixiAddTextAttribute.
So at this point I'm left wondering, what is the tixiUID function supposed to do?**

**Comment by Ofnir93** [comment]
Almost forgot, I'm currently using tixi ver. 2.2.4

**Comment by rainman110** [comment]
Hi,

sorry to reply this late. The problem is, that the xpath "/cpacs/vehicles/genericElements/genericElement" is not unique anymore, if you created the second element (there are two elements referring the same xpath).

Here's the solution

```matlab
for i = 1:n
  tixiCreateElement(tixi_h, '/cpacs/vehicles/genericElements', 'genericElement');
  UID = sprintf('myElement%dID', i);
  unique_xpath =sprintf('/cpacs/vehicles/genericElements/genericElement[%d]', i);
  tixiUIDSetToXPath(tixi_h, unique_xpath  , UID);
end
```
