### ISSUE TITLE
Deprecate Array Functions

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/tixi#142]
The functions

```
tixiGetArray
tixiGetArrayDimensionNames
tixiGetArrayDimensions
tixiGetArrayDimensionSizes
tixiGetArrayDimensionValues
tixiGetArrayElementCount
tixiGetArrayElementNames
tixiGetArrayParameterNames
tixiGetArrayParameters
tixiGetArrayValue
```

refer to a full-factorial map of values and are not used this way in CPACS anymore. In addition, the terminology might be confusing, as arrays in CPACS refer to something different. These functions should be marked deprecated for the next minor release, in case anyone is still using them. Then, possibly in a next major release, these functions can be removed/renamed.

**Comment by rainman110** [comment]
@joergbrech Currently, the functions are only deprecated for C and C++ users. Python / Fortran and Matlab users do not get informed about the deprecation.

Should we either 
 - Add a warning inside the function (which is probably very annoying)?
 - Or, extend the binding generator to produce a language-specific deprecation tag?

**Comment by joergbrech** [comment]
Hmm, good point! 

You are right about the first option to be very annoying, but on the other hand I am not sure how we would handle your second suggestion: In C and C++ deprecation warnings appear at compile time. For interpreted languages like python and matlab we won't get around throwing warnings: In Python we have a `DeprecationWarning`, for Matlab I don't know if there is a golden way to do this. So the way I see it, warnings are the only real option. And then I would much rather write them in C and have the binding generator take care of it, rather than having to bloat the bindings generator for language specific deprecation warnings.

**Comment by rainman110** [comment]
I agree, writing them in C is the most generic way and probably the way to go.
