### ISSUE TITLE
Rename GetNumberOfChilds to GetNumberOfChildren

### ISSUE THREAD

**Issue by ArneBachmannDLR** [DLR-SC/tixi#167]
Or: `GetChildrenCount` to miror the `GetNamedChildrenCount` naming.

**Comment by rainman110** [comment]
You're right w.r.t. consistency.

Renaming functions and changing the API is always a PITA for the users as they have to modify their source code. And if you're planning to support multiple version, then it gets even worse.

Therefore, I am against changing a function name if its not really pressuring.

**Comment by ArneBachmannDLR** [comment]
Why not create an alias (two signatures pointing to the same function) for two releases and then remove the old one? The old one could be marked as outdated. Not uncommon in frameworks.
