### ISSUE TITLE
MATLAB interface - incorrect call

### ISSUE THREAD

**Issue by CarstenChristmann** [DLR-SC/tixi#170]
This issue applies to both 32-bit and 64-bit 3.x-versions. Some MATLAB-functions included in ...\share\tixi3\matlab still call tixi_matlab and not tixi3_matlab. These functions only work after correction. The affected functions are:

tixiCheckAttribute.m
tixiCheckDocumentHandle.m
tixiCheckElement.m
tixiUIDCheckExists.m

In addition, ...\bin\tixi3.dll must be copied to ...\share\tixi3\matlab before tixi works with MATLAB.

**Comment by rainman110** [comment]
Hi. Thanks for the report! This is indeed an issue.

> In addition, ...\bin\tixi3.dll must be copied to ...\share\tixi3\matlab before tixi works with MATLAB.

We won't change this. We assuming, that the correct paths are set (e.g. via tixi installation) which would not require copying the dll intp the matlab folder. Otherwise, we would duplicate the DLL into different places.

**Comment by rainman110** [comment]
@CarstenChristmann Can you please test the fix by downloading the tixi build from here:
https://ci.appveyor.com/api/buildjobs/88f1q4debrtbwb2l/artifacts/TIXI-3.1.1-win64.zip

**Comment by CarstenChristmann** [comment]
@rainman110 I have tested the fix with my MATLAB script which uses only 2 out of the 4 mentioned functions. Both seem to work! Thank you!
