### ISSUE TITLE
Linux binaries missing from release page

### ISSUE THREAD

**Issue by danieljuschus** [DLR-SC/tixi#182]
The [wiki](https://github.com/DLR-SC/tixi/wiki/InstallationHowto) mentions that "Binaries for Windows and Linux can be downloaded from the releases page section." However, for the most recent version I can only see Windows releases and something called "Darwin" (not sure what that is). Or am I missing something?

In addition, the link to the "Open Build Service site" on [this wiki page](https://github.com/DLR-SC/tixi/wiki/Downloads) seems broken.

**Comment by rainman110** [comment]
Hi. Thanks for posting the issue. Darwin are macOS builds Linux binaries can be downloaded here via the package managers:

https://software.opensuse.org//download.html?project=science%3Adlr&package=tixi3

I'll update the wiki with the new link.
