### ISSUE TITLE
GetXPathFromUID should work with not-unique UIDs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-SC/tixi#35]
```
GetXPathFromUID should work with not-unique UIDs. The function should only 
check the uniqueness of the given UID.
```

Original issue reported on code.google.com by `markus.l...@gmail.com` on 22 Nov 2011 at 2:46

**Comment by rainman110** [comment]
This issue is not really an issue anymore, is it? You can simply use tixis txpath features and query the xpath.
