### ISSUE TITLE
Force writing of decimal point for float fields

### ISSUE THREAD

**Issue by sdeinert** [DLR-SC/tixi#73]
Tixi should force the output of decimal points for any float value in order to avoid confusion between integer and float fields during validation of xml files against an xml scheme.

**Comment by rainman110** [comment]
Does this mean, that number without decimal points are recognized as invalid according to the xml scheme?

**Comment by sdeinert** [comment]
No I just checked again. Only integer fields with decimal points are considered as invalid. The other way round works. From a user point of view I would find the decimal point more consistent.

**Comment by rainman110** [comment]
@sdeinert You know that you can specify the format of the output with the last argument of ```tixiAddFloatElement```. By default it is ```"%g"```. If you use ```"%f"``` instead, you have your digits after the comma.

**Comment by rainman110** [comment]
I close this issue, as the user can exacly specify the formatting of the output with the format flag.
