### ISSUE TITLE
location of tixi dll in python wrapper (windows)

### ISSUE THREAD

**Issue by immermarc** [DLR-SC/tixi#78]
In the tixiwrapper.py, the location of the dll is now specified by the windows DLL search order, requiring the tixi folder to be in PATH.
If the location of the dll would be provided in the wrapper, this could help depolyment of tixi as a python module. A proposed change would be:

```
if sys.platform == 'win32':
    folder = os.path.dirname(os.path.abspath(__file__))
    dll_path = os.path.join(folder, "TIXI.dll")
    lib = ctypes.CDLL(dll_path)
```

and of course adding os to the imports. It would then be straight forward to write a setup.py and create a pip installable python package.

**Comment by rainman110** [comment]
Thanks for your report. We won't change the behaviour of the loading location due two the following reasons:

 - We assume, that TIXI.dll is inside PATH. This is the case, we installing TiXI with the windows installer or using the linux packages.
 - By not providing the absolute PATH, we allow the user a more flexible way of integrating TiXI into their own project. This way, the tixiwrapper may not be inside the same directory as TIXI.dll
 - If you simple want to install TiXI for Python, you can use conda. Then, you don't have to tweak with paths etc. Please have a look here: https://anaconda.org/DLR-SC/tixi

**Comment by immermarc** [comment]
Thank you, I was not aware of the conda package. If not already in, this might be useful to mention in the documentation?

**Comment by rainman110** [comment]
Yes, you are right. This is still missing. On the TiGL page, we have some instructions, but here they are definitely missing.
