### ISSUE TITLE
tixiUIDCheckExists fails if any duplicate uID

### ISSUE THREAD

**Issue by codingpoets** [DLR-SC/tixi#83]
Recently I realized that the tixiUIDCheckExists function does not really answer the request if there is any douplicate uID. I wonder if we the check for douplicates should not rather be removed from this function.
![grafik](https://user-images.githubusercontent.com/10432668/27379408-64beb74c-567b-11e7-82b8-2a7fd573a154.png)
Is this not a different responsibility?
Of course uIDs should always be unique, but in case there are douplicate uIDs but the checked uID is not one of them, I think the function should not return the douplicate error.

**Comment by rainman110** [comment]
Yes, I think you are right! This should be a different concern.
