### ISSUE TITLE
missing return parameter for matlab binding for tixiUIDCheckExists

### ISSUE THREAD

**Issue by codingpoets** [DLR-SC/tixi#84]
Calling tixiUIDCheckExists from Matlab leads to an error.
The definition is missing the return parameter.
![grafik](https://user-images.githubusercontent.com/10432668/27379593-2ac21a2e-567c-11e7-8b1b-2ad199e8246f.png)

**Comment by rainman110** [comment]
This function is not generated automatically! It was written by hand (in a wrong way ;) ). 

We'll fix this.
