### ISSUE TITLE
3rd party libraries for VS2015

### ISSUE THREAD

**Issue by dixxi** [DLR-SC/tixi#94]
I would like to build TiGL with VS2015 (actually VS2017, but it is binary compatible with VS2015) and noted, that this is already done on your build servers and is part of your build scripts:
https://github.com/DLR-SC/tixi/blob/master/appveyor.yml

specifically the download of:
https://sourceforge.net/projects/tixi/files/dev-tools/tixi-3rdparty-vc2015-win64.zip

However, a direct link to the download is not yet added to the wiki:
https://github.com/DLR-SC/tixi/wiki/InstallationHowto#windows

Could you add a download link to your wiki? Or this this library bundle still an inofficial test version?

**Comment by rainman110** [comment]
@dixxi I added the links for the VC 2015 builds to the wiki.

The TiXI 3.0 Windows releases will be shipped with the VC 2015 toolchain by default.
