### ISSUE TITLE
find_package does not set TIXI_LIBRARIES

### ISSUE THREAD

**Issue by bernhardmgruber** [DLR-SC/tixi#96]
I tried cmake-configuring my CPACS generator as well as the cpacs_3 branch of TiGL with the 3.0.0 RC1 build of TIXI from https://github.com/DLR-SC/tixi/releases without success. After the find_package(TIXI ...) the cmake variable TIXI_LIBRARIES is always empty. I also tried printing all set cmake variables and couldn't find a suitable library variable for TIXI.
The TIXI_INCLUDE_DIRS variable is set correctly.

I tried the following calls (TIXI_PATH is set to the extracted TIXI-3.0.0rc1-win64 directory):
```
find_package(TIXI REQUIRED) # empty TIXI_LIBRARIES
find_package(TIXI 3.0.0 REQUIRED) # empty TIXI_LIBRARIES
find_package(TIXI 3.0.0rc1 REQUIRED) # cmake error with find_package argument
find_package(TIXI3 ... REQUIRED) # cmake error, cannot find a tixi3-config.cmake
```

I guess this is a problem with the packaging and the different project/lib name. My current workaround is to manually set the TIXI_LIBRARIES variable:
```
set(TIXI_LIBRARIES ${TIXI_PATH}/lib/tixi3.lib)
```

**Comment by rainman110** [comment]
@joergbrech  The bug is to find here:
https://github.com/DLR-SC/tixi/blob/master/contrib/tixi-config.cmake.in#L18

It actually must be @TIXI_LIB_NAME@

**Comment by rainman110** [comment]
@dixxi As a better workaround, use
```
set(TIXI_LIBRARIES tixi3)
```

for now.

**Comment by rainman110** [comment]
@bernhardmgruber The cmake scripts seem to work now on my computer. Could you please check, whether this problem is solved for you as well?

You can download the generated binaries directly from the CI system.

**Comment by bernhardmgruber** [comment]
@rainman110 good work! The CPACS generator and TIGL now find and correctly link tixi3
